name: CD - Release all packages

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Format
      run: dotnet format --verify-no-changes --no-restore
    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore
    - name: Test
      run: dotnet test -c $BUILD_CONFIG --no-build --verbosity normal
