name: CD - Release all packages

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Format
      run: dotnet format --verify-no-changes --no-restore

    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore

    - name: Test
      run: dotnet test -c $BUILD_CONFIG --no-build --verbosity normal

    - name: Package Peter.MinimalAPI
      run: dotnet pack -c $BUILD_CONFIG src/Peter.MinimalAPI/Peter.MinimalAPI.csproj

    - name: Package Peter.Result
      run: dotnet pack -c $BUILD_CONFIG src/Peter.Result/Peter.Result.csproj

    - name: Package Peter.Result.MinimalAPI
      run: dotnet pack -c $BUILD_CONFIG src/Peter.Result.MinimalAPI/Peter.Result.MinimalAPI.csproj

    - name: Package Peter.MinimalApi.MediatR
      run: dotnet pack -c $BUILD_CONFIG src/Peter.MinimalApi.MediatR/Peter.MinimalApi.MediatR.csproj

    - name: Publish
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet nuget push .\src\Peter\bin\Release\*.nupkg --source https://api.nuget.org/v3/index.json --api-key $env:NUGET_API_KEY --skip-duplicate
      shell: pwsh
      env:
        NUGET_API_KEY:  ${{ secrets.NUGET_API_KEY }}

    # - name: Upload a Build Artifact
    #   uses: actions/upload-artifact@v2.2.2
    #   with:
    #     path: src/Peter/bin/${{ env.BUILD_CONFIG }}    