name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
    - '.idea/**'
    - '.vs/**'
    - 'docs/**'    
  pull_request:
    paths-ignore:
    - '**/README.md'
    - '.idea/**'
    - '.vs/**'
    - 'docs/**'    

jobs:
  build:
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Format
      run: dotnet format --verify-no-changes --no-restore
    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore
    - name: Test
      run: dotnet test -c $BUILD_CONFIG --no-build --verbosity normal
