name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
    - '.idea/**'
    - '.vs/**'
    - 'docs/**'    
  pull_request:
    paths-ignore:
    - '**/README.md'
    - '.idea/**'
    - '.vs/**'
    - 'docs/**'    

jobs:
  build:
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    # - name: Format
    #   run: dotnet format --verify-no-changes --no-restore

    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore

    - name: Test
      run: dotnet test -c $BUILD_CONFIG --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  /p:CoverletOutput=./TestResults/Coverage

    - name: Code Coverage Report
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            filename: coverage/**/coverage.cobertura.xml
            badge: true
            fail_below_min: true
            format: markdown
            hide_branch_rate: false
            hide_complexity: true
            indicators: true
            output: both
            thresholds: '70 90'
